name: Continuos Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Clonando repositorio
        uses: actions/checkout@v3

      - name: Configurando JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Teste e Build com Maven
        run: mvn -B -q install

      - name: Teste com Checkstyle
        run: mvn checkstyle:check
